front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    # - mongo:mongo
    # - memcached:memcached
    # - redis:redis
    # - elasticsearch:elasticsearch
    # - rabbitmq:rabbitmq
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: alterway/mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQLD__max_allowed_packet: "150M"
    MYSQLD__character_set_server: 'utf8'
    MYSQLD__character_set_filesystem: 'utf8'
    MYSQLD__collation-server: 'utf8_general_ci'

# mongo:
#   image: mongo
#   ports:
#     - "27017:27017"
# 
# memcached:
#   image: memcached
#   ports:
#     - "11211:11211"
# 
# redis:
#   image: redis
#   ports:
#     - "6379:6379"
# 
# elasticsearch:
#   image: elasticsearch
#   ports:
#     - "9200:9200"
#     - "9300:9300"
# 
# rabbitmq:
#   image: rabbitmq:3.6.1-management
#   ports:
#     - "15672:15672"
#     - "5672:5672"
# 
